# Generated by Django 4.2 on 2023-05-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_registration_email_alter_registration_phone1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=22)),
                ('lastname', models.CharField(max_length=6)),
                ('date', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(max_length=22)),
                ('country', models.CharField(max_length=30)),
                ('town', models.IntegerField()),
                ('state', models.CharField(max_length=30)),
                ('num1', models.CharField(max_length=30)),
                ('num2', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
